### ISSUE TITLE
refactor library kex and cipher implementation

### ISSUE THREAD

**Issue by chris-rock** [dev-sec/chef-ssh-hardening#87]
- better structure
- easier to upgrade ciphers to new os
- reduce robocop abc metric

**Comment by chris-rock** [comment]
should revert #86

**Comment by artem-sidorenko** [comment]
@chris-rock I guess we differentiate [here](https://github.com/dev-sec/chef-ssh-hardening/blob/master/libraries/get_ssh_ciphers.rb#L30-L36) between different OpenSSH versions. What about not to use the OS detection, but to use the openssh version in order to determine the supported ciphers?

We [know](https://github.com/dev-sec/chef-ssh-hardening/blob/master/attributes/default.rb) the package name of openssh, and can get the version via information provided by ohai.

What do you think about this approach?

**Comment by artem-sidorenko** [comment]
me and @atomic111 agreed to push everything besides #132 to the 2.0.0, so I'm changing the milestone
